# Generated by Django 5.1.2 on 2024-12-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='patil',
        ),
    ]
